# International Unemployment Rate Data

Download all available data from https://data.oecd.org/unemp/unemployment-rate.htm

In [1]:
import pandas as pd

In [2]:
# Country abbreviations
abbreviations = {'AUS':'Australia',
                 'AUT':'Austria',
                 'BEL':'Belgium',
                 'BRA':'Brazil',
                 'CAN':'Canada',
                 'CHL':'Chile',
                 'COL':'Colombia',
                 'CZE':'Czech Republic',
                 'CHE':'Switzerland',
                 'DEU':'Germany',
                 'DNK':'Denmark',
                 'EA19':'Euro Area (19 countries)',
                 'ESP':'Spain',
                 'EST':'Estonia',
                 'EU28':'European Union (28 countries)',
                 'FIN':'Finland',
                 'FRA':'France',
                 'GBR':'Great Britain',
                 'GRC':'Greece',
                 'HUN':'Hungary',
                 'IDN':'Indonesia',
                 'IRL':'Ireland',
                 'ISL':'Iceland',
                 'ISR':'Israel',
                 'ITA':'Italy',
                 'JPN':'Japan',
                 'KOR':'South Korea',
                 'LTU':'Lithuania',
                 'LUX':'Luxemburg',
                 'LVA':'Latvia',
                 'MEX':'Mexico',
                 'NLD':'Netherlands',
                 'NOR':'Norway',
                 'NZL':'New Zealand',
                 'OECD':'OECD',
                 'POL':'Poland',
                 'PRT':'Portugal',
                 'RUS':'Russia',
                 'SVK':'Slovak Republic',
                 'SVN':'Slovenia',
                 'SWE':'Sweden',
                 'TUR':'Turkey',
                 'USA':'United States',
                 'ZAF':'South Africa'
                }

In [8]:
# Import data
# data = pd.read_csv('../csv/DP_LIVE_14052019055753603.csv')
data = pd.read_csv('../csv/DP_LIVE_14052019064354113.csv')

# # Manage data
# data = data[(data.FREQUENCY=='A') & (data.SUBJECT=='TOT')]

# # Construct dataset
# df = pd.DataFrame()

# for code in data.LOCATION.sort_values().unique():
    
#     values = data[data.LOCATION==code].Value
#     index = pd.to_datetime(data[data.LOCATION==code].TIME.astype(str))

#     temp_series = pd.Series(values)
#     temp_series.index=index

#     df[abbreviations[code]] = temp_series

# # Rename index column
# df.index.name='Date'

# # Export data
# df.to_csv('../csv/international_unemployment_rate_data.csv')

FileNotFoundError: File b'../csv/DP_LIVE_14052019064354113.csv' does not exist

In [4]:
df

,Australia,Austria,Belgium,Brazil,Canada,Switzerland,Chile,Colombia,Czech Republic,Germany,...,OECD,Poland,Portugal,Russia,Slovak Republic,Slovenia,Sweden,Turkey,United States,South Africa
Date,,,,,,,,,,,,,,,,,,,,,
1967-01-01,1.875000,NaN,NaN,NaN,3.833333,NaN,NaN,NaN,NaN,1.349086,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.841667,NaN
1968-01-01,1.850000,NaN,NaN,NaN,4.525000,NaN,NaN,NaN,NaN,0.956745,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.583333,NaN
1969-01-01,1.800000,2.038766,NaN,NaN,4.425000,NaN,NaN,NaN,NaN,0.523999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.508333,NaN
1970-01-01,1.625000,1.412589,NaN,NaN,5.675000,NaN,NaN,NaN,NaN,0.431555,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.933333,NaN
1971-01-01,1.925000,1.238531,NaN,NaN,6.200000,NaN,NaN,NaN,NaN,0.533070,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.958333,NaN
1972-01-01,2.625000,1.164418,NaN,NaN,6.233333,NaN,NaN,NaN,NaN,0.709575,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.616667,NaN
1973-01-01,2.325000,1.084896,NaN,NaN,5.566667,NaN,NaN,NaN,NaN,0.781361,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.891667,NaN
1974-01-01,2.700000,1.345436,NaN,NaN,5.333333,NaN,NaN,NaN,NaN,1.666524,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.591667,NaN
1975-01-01,4.925000,1.752424,NaN,NaN,6.916667,NaN,NaN,NaN,NaN,3.103751,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.466666,NaN
1976-01-01,4.750000,1.809018,NaN,NaN,7.083333,NaN,NaN,NaN,NaN,3.090683,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.716667,NaN
1977-01-01,5.650000,1.638162,NaN,NaN,8.058333,NaN,NaN,NaN,NaN,3.009056,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.066667,NaN
1978-01-01,6.442533,2.062655,NaN,NaN,8.383333,NaN,NaN,NaN,NaN,2.889838,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.066667,NaN
1979-01-01,6.265499,2.104195,NaN,NaN,7.550000,NaN,NaN,NaN,NaN,2.528004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.833333,NaN
1980-01-01,6.106246,1.854277,NaN,NaN,7.550000,NaN,NaN,NaN,NaN,2.469315,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.141667,NaN
1981-01-01,5.783571,2.515609,NaN,14.112940,7.633333,NaN,NaN,NaN,NaN,3.487885,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.600000,NaN
1982-01-01,7.156132,3.464959,NaN,11.192400,11.033330,NaN,NaN,NaN,NaN,4.983604,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.708333,NaN
1983-01-01,9.961594,4.107561,NaN,11.966450,12.033330,NaN,NaN,NaN,NaN,6.131380,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.616667,NaN
1984-01-01,8.989680,3.800045,NaN,12.712210,11.350000,NaN,NaN,NaN,NaN,6.139421,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.525000,NaN
1985-01-01,8.262986,3.599384,NaN,9.388283,10.666670,NaN,NaN,NaN,NaN,6.193343,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.191667,NaN
1986-01-01,8.081038,3.134631,NaN,6.420115,9.675000,NaN,12.115000,NaN,NaN,5.929549,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.991667,NaN
1987-01-01,8.108040,3.794924,NaN,6.670191,8.833333,NaN,10.927500,NaN,NaN,5.891681,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.191667,NaN
1988-01-01,7.227954,3.563734,NaN,6.874122,7.766667,NaN,9.752500,NaN,NaN,5.878985,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.491667,NaN
1989-01-01,6.179825,3.132628,NaN,5.989923,7.566667,NaN,7.902500,NaN,NaN,5.311517,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.266667,NaN
1990-01-01,6.923000,3.240462,NaN,7.649656,8.150000,NaN,7.757500,NaN,NaN,4.817337,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.616667,NaN
1991-01-01,9.576522,3.475676,NaN,8.628675,10.325000,NaN,8.155000,NaN,NaN,5.569215,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.816667,NaN
1992-01-01,10.728140,3.593146,NaN,10.113210,11.191670,NaN,6.665000,NaN,NaN,6.621125,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.508333,NaN
1993-01-01,10.874670,4.217466,NaN,9.495458,11.400000,NaN,6.542500,NaN,NaN,7.869413,...,NaN,NaN,NaN,5.291667,NaN,NaN,NaN,NaN,6.900000,NaN
1994-01-01,9.722190,3.577942,NaN,9.046363,10.416670,NaN,7.815000,NaN,NaN,8.401136,...,NaN,NaN,NaN,7.016667,13.655170,NaN,NaN,NaN,6.083333,NaN
1995-01-01,8.472281,3.699785,NaN,8.297771,9.508333,NaN,7.302500,NaN,NaN,8.126454,...,NaN,NaN,NaN,8.266666,13.113460,NaN,NaN,NaN,5.608333,NaN
1996-01-01,8.506114,4.139831,NaN,9.698496,9.608334,NaN,6.325000,NaN,NaN,8.863040,...,NaN,NaN,NaN,9.591666,11.328770,NaN,NaN,NaN,5.416667,NaN
1997-01-01,8.362488,4.242406,NaN,10.120500,9.116667,NaN,6.115000,NaN,NaN,9.817107,...,NaN,NaN,NaN,10.808330,11.874550,NaN,NaN,NaN,4.950000,NaN
1998-01-01,7.677429,4.235766,NaN,13.579890,8.283334,NaN,6.395000,NaN,6.476871,9.201705,...,NaN,NaN,5.072283,11.875000,12.603920,NaN,NaN,NaN,4.508333,NaN
1999-01-01,6.873791,3.727968,8.561709,13.498170,7.591667,NaN,10.137500,NaN,8.755593,8.414573,...,NaN,NaN,4.515511,12.916670,16.352170,7.417529,NaN,NaN,4.216667,NaN
2000-01-01,6.285546,3.533025,7.009650,12.747940,6.816667,NaN,9.667500,NaN,8.823602,7.755578,...,NaN,16.106120,4.029012,10.491670,18.757500,6.731878,NaN,NaN,3.991667,23.300
2001-01-01,6.742173,3.590860,6.607931,11.174870,7.216667,NaN,9.852500,NaN,8.165375,7.836031,...,NaN,18.243220,4.008832,9.033334,19.305970,6.175611,4.850808,NaN,4.733333,26.200
2002-01-01,6.368911,3.951978,7.511277,11.728850,7.675000,NaN,9.805000,NaN,7.313614,8.653863,...,NaN,19.932720,4.993313,8.000000,18.671330,6.310935,5.072618,NaN,5.775000,26.600
2003-01-01,5.928420,4.286487,8.172144,12.413030,7.575000,NaN,9.540000,NaN,7.812037,9.637083,...,NaN,19.619640,6.264945,8.625000,17.555150,6.675458,5.677462,NaN,5.991667,24.800
2004-01-01,5.396734,5.490250,8.387378,11.550470,7.191667,NaN,10.007500,NaN,8.322025,9.793687,...,NaN,18.978370,6.622547,8.158334,18.224490,6.294299,6.525636,NaN,5.533333,23.000
2005-01-01,5.033881,5.628417,8.438975,9.889733,6.758333,NaN,9.235000,NaN,7.928005,11.167680,...,6.569622,17.752690,7.580669,7.558333,16.258930,6.503201,7.475815,NaN,5.066667,23.500
2006-01-01,4.785240,5.246718,8.249064,10.029630,6.333333,NaN,7.800000,NaN,7.148034,10.252720,...,6.057565,13.848890,7.647437,7.166667,13.372620,5.952952,7.068759,8.750455,4.616667,22.100
2007-01-01,4.379151,4.858952,7.459264,9.348774,6.050000,NaN,7.130000,11.222500,5.321516,8.661530,...,5.596682,9.607605,7.963667,6.125000,11.144810,4.824745,6.163466,8.887152,4.616667,21.000
2008-01-01,4.234330,4.129104,6.970808,7.928607,6.141667,NaN,7.792500,11.277500,4.392356,7.527764,...,5.929479,7.120995,7.551991,6.358333,9.512194,4.375046,6.234297,9.728543,5.775000,22.525
2009-01-01,5.560385,5.298988,7.906314,8.108846,8.350000,NaN,9.675000,12.080000,6.658732,7.743155,...,8.104794,8.166371,9.432886,8.375000,12.017910,5.847313,8.346865,12.580590,9.266666,23.700
2010-01-01,5.213340,4.821680,8.293048,6.757159,8.058333,4.807282,8.150000,11.841670,7.279707,6.967637,...,8.312364,9.640347,10.769820,7.483333,14.381030,7.237447,8.610753,10.684520,9.616667,24.875
2011-01-01,5.081195,4.566622,7.139795,5.978367,7.525000,4.406741,7.125000,10.895000,6.711369,5.827424,...,7.938690,9.632815,12.681060,6.499474,13.617580,8.169436,7.803870,8.814762,8.950000,24.800
2012-01-01,5.223376,4.863267,7.537931,5.520268,7.291667,4.483940,6.432676,10.434170,6.977849,5.380757,...,7.936302,10.088820,15.530280,5.462007,13.963350,8.838806,7.975423,8.166607,8.066667,24.875
2013-01-01,5.661940,5.336031,8.425185,5.400495,7.083333,4.746688,5.932378,9.705833,6.953799,5.231962,...,7.876283,10.328620,16.183800,5.485319,14.221330,10.108590,8.052903,8.740033,7.375000,24.725
2014-01-01,6.077244,5.621219,8.522890,4.851514,6.908333,4.829303,6.391404,9.166667,6.109115,4.981592,...,7.356270,8.990872,13.895090,5.157500,13.184280,9.673278,7.955972,9.883171,6.166667,25.100
2015-01-01,6.056423,5.723468,8.481071,NaN,6.908333,4.800180,6.213719,8.960834,5.046221,4.624955,...,6.770274,7.503080,12.444690,5.568395,11.482270,8.962607,7.432082,10.244970,5.291667,25.350
2016-01-01,5.710301,6.014071,7.833329,NaN,6.991667,4.918711,6.490013,9.274167,3.952049,4.122733,...,6.327960,6.161703,11.068460,5.538820,9.671689,8.006598,6.991096,10.838120,4.866667,26.725
2017-01-01,5.593747,5.500528,7.088736,NaN,6.341667,4.797114,6.673688,9.425834,2.890817,3.746631,...,5.768556,4.887239,8.870407,5.212452,8.130965,6.569075,6.718704,10.833030,4.350000,27.450
2018-01-01,5.299963,4.848801,5.949855,NaN,5.833333,4.714227,6.966212,9.719167,2.243518,3.384090,...,5.296470,3.846072,6.994051,4.802335,6.536399,5.110229,6.346331,10.887480,3.900000,27.125

In [7]:
data.LOCATION.unique()

array(['AUS', 'AUT', 'BEL', 'CAN', 'CZE', 'DNK', 'FIN', 'FRA', 'DEU',
       'GRC', 'HUN', 'ISL', 'IRL', 'ITA', 'JPN', 'KOR', 'LUX', 'MEX',
       'NLD', 'NZL', 'NOR', 'POL', 'PRT', 'SVK', 'ESP', 'SWE', 'CHE',
       'TUR', 'GBR', 'USA', 'BRA', 'CHL', 'EST', 'IDN', 'ISR', 'RUS',
       'SVN', 'ZAF', 'EU28', 'OECD', 'EA19', 'COL', 'LVA', 'LTU'],
      dtype=object)